export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    price: 450000,
    stock: 12,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=500&q=80",
    description: "Headphonewireless dengan suara jernih dan nyaman digunakan sehari-hari.",
  },
  {
    id: 2,
    name: "Smart Watch",
    slug: "smart-watch",
    price: 650000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=80",
    description: "Smart watch dengan desain modern yang cocok digunakan untuk aktivitas sehari-hari.",
  },
    {
    id: 3,
    name: "Laptop Pro",
    slug: "laptop-pro",
    price: 8500000,
    stock: 5,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=500&q=80",
    description: "Laptop dengan desain modern dan performa yang cocok untuk kebutuhan kerja dan belajar.",
  },
  {
    id: 4,
    name: "Bluetooth Speaker",
    slug: "bluetooth-speaker",
    price: 350000,
    stock: 10,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=500&q=80",
    description: "Bluetooth speaker dengan suara jernih dan desain praktis untuk digunakan di berbagai tempat.",
  },
  {
    id: 5,
    name: "Kaos Casual",
    slug: "kaos-casual",
    price: 120000,
    stock: 20,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=80",
    description: "Kaos casual dengan desain sederhana yang nyaman digunakan untuk aktivitas sehari-hari.",
  },
  {
    id: 6,
    name: "Jaket Kulit",
    slug: "jaket-kulit",
    price: 350000,
    stock: 8,
    category: 2,
    category_name: "Fashion",
    rating: 5,
   img: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=500&q=80",
    description: "Jaket kulit dengan desain casual yang cocok dipadukan dengan berbagai gaya pakaian.",
  },
  {
    id: 7,
    name: "Tas Ransel",
    slug: "tas-ransel",
    price: 250000,
    stock: 12,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=500&q=80",
    description: "Tas ransel dengan ruang penyimpanan yang praktis untuk membawa berbagai kebutuhan.",
  },
  {
    id: 8,
    name: "Face Wash",
    slug: "face-wash",
    price: 85000,
    stock: 25,
    category: 3,
    category_name: "Kecantikan",
    rating: 5,
    img: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=500&q=80",
    description: "Face wash yang membantu membersihkan wajah dan menjaga kulit tetap terasa segar.",
  },
  {
    id: 9,
    name: "Moisturizer",
    slug: "moisturizer",
    price: 150000,
    stock: 15,
    category: 3,
    category_name: "Kecantikan",
    rating: 4,
    img: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=500&q=80",
    description: "Moisturizer untuk membantu menjaga kelembapan kulit agar terasa lembut dan nyaman.",
  },
  {
    id: 10,
    name: "Sunscreen",
    slug: "sunscreen",
    price: 95000,
    stock: 18,
    category: 3,
    category_name: "Kecantikan",
    rating: 5,
    img: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=500&q=80",
    description: "Sunscreen untuk membantu melindungi kulit dari paparan sinar matahari saat beraktivitas.",
  },
    {
    id: 11,
    name: "Cushion",
    slug: "cushion",
    price: 125000,
    stock: 15,
    category: 3,
    category_name: "Kecantikan",
    rating: 5,
    img: "https://images.unsplash.com/photo-1768369712397-f1a9fa19ea27?auto=format&fit=crop&w=600&q=80",
    description: "Cushion dengan tekstur ringan yang membantu memberikan tampilan wajah lebih merata.",
  },
  {
    id: 12,
    name: "Celana Kulot",
    slug: "celana-kulot",
    price: 175000,
    stock: 12,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80",
    description: "Celana kulot dengan desain nyaman dan cocok digunakan untuk berbagai aktivitas.",
  },
  {
    id: 13,
    name: "Dress Wanita",
    slug: "dress-wanita",
    price: 250000,
    stock: 10,
    category: 2,
    category_name: "Fashion",
    rating: 5,
    img: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80",
    description: "Dress wanita dengan desain simpel dan elegan yang cocok digunakan untuk berbagai acara.",
  },
  {
    id: 14,
    name: "Handphone",
    slug: "handphone",
    price: 3500000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
    description: "Handphone dengan desain modern yang cocok digunakan untuk komunikasi dan kebutuhan sehari-hari.",
  },
  {
    id: 15,
    name: "Lipstik",
    slug: "lipstik",
    price: 95000,
    stock: 18,
    category: 3,
    category_name: "Kecantikan",
    rating: 5,
    img: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&q=80",
    description: "Lipstik dengan warna yang menarik untuk melengkapi tampilan makeup sehari-hari.",
  },
  {
    id: 16,
    name: "Kacamata",
    slug: "kacamata",
    price: 150000,
    stock: 14,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80",
     description: "Kacamata dengan desain modern yang cocok digunakan sebagai pelengkap gaya sehari-hari.",
  },
];